apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo-demo
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: 'https://github.com/dordor22/nginx-argo-demo.git'
    targetRevision: main
    path: manifests 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-project
  syncPolicy:
    automated:
      prune: true         
      selfHeal: true       
    syncOptions:
      - CreateNamespace=true

